buildscript {
    ext {
        springBootVersion = '3.4.4' 
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }
}

allprojects {
    group = 'com.qualentraglobal.astraq'
    version = '1.0.0'
    repositories {
        mavenCentral()
    }
}

subprojects {
   apply plugin: 'org.springframework.boot'
   apply plugin: 'io.spring.dependency-management'
   apply plugin: 'java'
    
    sourceCompatibility = '21' // or your version
    targetCompatibility = '21'

    dependencies {
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
         // Lombok
    	compileOnly 'org.projectlombok:lombok:1.18.30'
    	annotationProcessor 'org.projectlombok:lombok:1.18.30'
    }
    bootJar {
    enabled = false
	}
    
}
