plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}


dependencies {
    implementation project(':AstraQ-Common')
   	implementation project(':AstraQ-Model')
   	implementation project(':AstraQ-Repository')
   	implementation project(':AstraQ-Service')
    implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-web-services'
    implementation 'org.springframework.boot:spring-boot-starter-security'
	//compileOnly 'org.projectlombok:lombok'
	compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
	implementation 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.6'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    // PostgreSQL driver
    runtimeOnly 'org.postgresql:postgresql'
}

repositories {
    mavenCentral()
}

bootJar {
    enabled = true
	}
